$font = Adwaita Sans

general {
    hide_cursor = true
}

animations {
    enabled = false
}

background {
    monitor = eDP-1
    path = ~/Pictures/wallpapers/wallpaper.jpg
    blur_passes = 3
}

label {
    text = cmd[update:60000] date +"%A, %B %d"
    font_size = 25
    font_family = $font
    position = 0, 40
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] date +"<span font_weight=\"semibold\">%I:%M %p</span>"
    font_size = 50
    font_family = $font
    position = 0, -20
    halign = center
    valign = center
}
